export const methods = {
    get: "GET",
    post: "POST",
    put: "PUT",
    patch: "PATCH",
    delete: "DELETE",
    head: "HEAD",
    options: "OPTIONS",
    connect: "CONNECT",
    trace: "TRACE",
    copy: "COPY",
    move: "MOVE",
    mkCol: "MKCOL",
    propFind: "PROPFIND",
    propPatch: "PROPPATCH",
    lock: "LOCK",
    unlock: "UNLOCK",
    subscribe: "SUBSCRIBE",
    unsubscribe: "UNSUBSCRIBE",
    report: "REPORT",
    merge: "MERGE",
    patchMerge: "PATCHMERGE",
} as const;
